version: "3"
services:

  petclinic:
    image: paulczar/petclinic:2.1.0.BUILD-SNAPSHOT-143bea7
    ports:
      - "8080:8080/tcp"
    environment:
      - DATABASE_PASSWORD=petclinic
      - DATABASE_USERNAME=petclinic
      - DATABASE_NAME=petclinic
      - DATABASE_ENGINE=mysql
      - DATABASE_HOST=database
      - SPRING_PROFILES_ACTIVE=docker
  database:
    image: mysql:5.7
    ports:
      - "3306/tcp"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_PASSWORD=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_DATABASE=petclinic
