nameOverride: dev-petclinic
fullnameOverride: dev-petclinic

image:
  repository: paulczar/petclinic
  tag: latest
  pullPolicy: Always

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: gce
  hosts:
    - dev-petclinic.pivlab.gcp.paulczar.wtf

service:
  type: NodePort

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/actuator/prometheus"

javaToolOptions: "-Xmx500m"

spring:
  kubernetes: false
  config:
    content: |
      spring:
        devtools.add-properties: false
        datasource:
          initialize: true
          schema: "classpath*:db/mysql/schema.sql"
          data: "classpath*:db/mysql/data.sql"
          url: "jdbc:mysql://${database.host}/${database.name}"
          username: ${database.username}
          password: ${database.password}
        #jpa.generate-ddl: false
        #jpa.hibernate.ddl: create
        #jpa.hibernate.ddl-auto: update
        #jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        #jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      database.host: petclinic-dev-db-mysql
      database.name: petclinic
      database.username: root
      database.password: shitty-root-password
      database.engine: mysql

resources:
  limits:
   cpu: 500m
   memory: 512Mi
  requests:
   cpu: 500m
   memory: 512Mi

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 300
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10