spring:
  profiles:
    active: development
  datasource:
    scheme: classpath*:db/${database.engine}/schema.sql
    data: classpath*:db/${database.engine}/data.sql
    # Uncomment this the first time the app runs
    initialization-mode: always
  thymeleaf:
    mode: HTML
  jpa.hibernate.ddl-auth: none
  messages.basename: messages/messages
  resources.cache.cachecontrol.max-age: 12h

database:
  engine: hsqldb
  host: database
  name: petclinic
  username: petclinic
  password: petclinic
# Actuator / Management
management.endpoints.web.base-path: /manage
management.endpoints.web.exposure.include: "*"

# Logging
logging.level.org.springframework: INFO
# logging.level.org.springframework.web: DEBUG
# logging.level.org.springframework.context.annotation: TRACE

# Maximum time static resources should be cached
spring.resources.cache.cachecontrol.max-age: 12h

---
spring:
  profiles: docker
  datasource:
    url: "jdbc:mysql://${database.host}/${database.name}"
    username: ${database.username}
    password: ${database.password}
    # Uncomment this the first time the app runs
    #initialization-mode: always
database.engine: mysql
---
spring:
  profiles: kubernetes
---
spring:
  profiles: development
database: hsqldb